version: 2

sources:
  - name: erp
    description: 'This is the ERP sources from adventure works. With data from sales, products, HR, and others.'
    database: fea24_6
    schema: raw_adventure_works
    tables:
      - name: product
        description: 'Table with product data'
        columns:
          - name: productid
            description: 'Chave primária da tabela funcionários.Primary key for product records.'
            tests:
              - unique
              - not_null
      - name: productsubcategory
        description:  'Products subcategories.'
        columns:
          - name: productsubcategoryid
            description: 'Primary key for Product Subcategory records.'
            tests:
              - unique
              - not_null
      - name: productcategory
        description: 'High-level product categorization.'
        columns:
          - name: productcategoryid
            description: 'Primary key for Product Category records'
            tests:
              - unique 
              - not_null